=== Nemzag/Gheg-Both/MicrosoftOpenOfficeFilesAndResearch/2019‑02‑02_-_Albanian_Languages_list_Access_backup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Albanian_Languages" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Albanian_Languages">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Albanian_Languages" index-key="Albanian_Languages " primary="no" unique="yes" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="Albanina_Languages_ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="rcmGNeZr/Ea/JTe8tSUY+Q==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACtyYY15mv8Rr8lN7y1JRj5AAAAANc5BnTNCuVAAAAAAAAAAABBAGwA
YgBhAG4AaQBhAG4AXwBMAGEAbgBnAHUAYQBnAGUAcwAAAAAAAABGHa7PKj1rS5bz
mc4MOyNABwAAAK3JhjXma/xGvyU3vLUlGPlBAGwAYgBhAG4AaQBuAGEAXwBMAGEA
bgBnAHUAYQBnAGUAcwBfAEkARAAAAAAAAADxCJ7B6YhIQ5GSr5Ya4GelBwAAAK3J
hjXma/xGvyU3vLUlGPlBAGwAYgBhAG4AaQBhAG4AXwBMAGEAbgBnAHUAYQBnAGUA
cwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Albanian_Languages" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="8QiewemISEORkq+WGuBnpQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="32"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Albanina_Languages_ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Rh2uzyo9a0uW85nODDsjQA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Nemzag/Gheg-Both/MicrosoftOpenOfficeFilesAndResearch/2019‑02‑02_-_Albanian_Languages_list_Access_backup.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="2019‑02‑02_-_Albanian_Languages_list_Access_backup.xsd" generated="2019-02-02T23:42:32">
<Albanian_Languages>
<Albanian_Languages>Jllvrianishtë</Albanian_Languages>
<Albanina_Languages_ID>1</Albanina_Languages_ID>
</Albanian_Languages>
<Albanian_Languages>
<Albanian_Languages>Qrêguishtë</Albanian_Languages>
<Albanina_Languages_ID>2</Albanina_Languages_ID>
</Albanian_Languages>
<Albanian_Languages>
<Albanian_Languages>Latinishtë</Albanian_Languages>
<Albanina_Languages_ID>3</Albanina_Languages_ID>
</Albanian_Languages>
<Albanian_Languages>
<Albanian_Languages>Persishtë</Albanian_Languages>
<Albanina_Languages_ID>4</Albanina_Languages_ID>
</Albanian_Languages>
<Albanian_Languages>
<Albanian_Languages>Shemitikishtë</Albanian_Languages>
<Albanina_Languages_ID>5</Albanina_Languages_ID>
</Albanian_Languages>
<Albanian_Languages>
<Albanian_Languages>Slavikishtë</Albanian_Languages>
<Albanina_Languages_ID>6</Albanina_Languages_ID>
</Albanian_Languages>
<Albanian_Languages>
<Albanian_Languages>Hindianishtë</Albanian_Languages>
<Albanina_Languages_ID>7</Albanina_Languages_ID>
</Albanian_Languages>
<Albanian_Languages>
<Albanian_Languages>Zhermanishtë</Albanian_Languages>
<Albanina_Languages_ID>8</Albanina_Languages_ID>
</Albanian_Languages>
<Albanian_Languages>
<Albanian_Languages>Altaikishtë</Albanian_Languages>
<Albanina_Languages_ID>9</Albanina_Languages_ID>
</Albanian_Languages>
</dataroot>
